### ISSUE TITLE
What is the intention of using the "multi" option here?

### ISSUE THREAD

**Issue by yujong-lee** [dooboolab/eslint-config#6]
https://github.com/dooboolab/eslint-config/blob/724eab91c56fab96257f792ee43b9c93359f6697/index.js#L57

I'm curious why "multi" option is used. I think it should be removed.
If there's a story I don't know, please let me know. 😄 

[Reference 1](https://eslint.org/docs/rules/curly)

>JavaScript allows the omission of curly braces when a block contains only one statement. However, it is considered by many to be best practice to never omit curly braces around blocks, even when they are optional, because it can lead to bugs and reduces code clarity. So the following:

[Reference 2](https://embeddedgurus.com/barr-code/2014/03/apples-gotofail-ssl-security-bug-was-easily-preventable/)

>Had Apple not violated this always-braces rule in the SSL/TLS code above, there would have been either just one set of curly braces after each if test or a very odd looking hard-to-miss chunk of code with two sets of curly braces after the if with two gotos. Either way, this bug was preventable by following this rule and performing code review.

**Comment by hyochan** [comment]
Thanks for the detail~! Agree with your statement.
